# .github/labeler.yml
# Automatically labels PRs based on which files changed.

api:
  - changed-files:
    - any-glob-to-any-file: 'FitPlay.Api/**'

blazor:
  - changed-files:
    - any-glob-to-any-file: 'FitPlay-Blazor/**'

domain:
  - changed-files:
    - any-glob-to-any-file: 'FitPlay.Domain/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'FitPlay.tests/**'

ci/cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

docker:
  - changed-files:
    - any-glob-to-any-file: '**/Dockerfile'
