@FitPlay.Api_HostAddress = http://localhost:5179

GET {{FitPlay.Api_HostAddress}}/weatherforecast
Accept: application/json

GET {{FitPlay.Api_HostAddress}}/api/Exercises
Accept: application/json

GET {{FitPlay.Api_HostAddress}}/api/TeacherProfiles
Accept: application/json

GET {{FitPlay.Api_HostAddress}}/api/Leaderboards
Accept: application/json
